/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package service.template;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        //App classUnderTest = new App();
        String result = "hola".concat("r");
        assertNotNull("app should have a greeting", result);
    }
}
